require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KeywordsController do

  # This should return the minimal set of attributes required to create a valid
  # Keyword. As you add validations to Keyword, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KeywordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all keywords as @keywords" do
      keyword = Keyword.create! valid_attributes
      get :index, {}, valid_session
      assigns(:keywords).should eq([keyword])
    end
  end

  describe "GET show" do
    it "assigns the requested keyword as @keyword" do
      keyword = Keyword.create! valid_attributes
      get :show, {:id => keyword.to_param}, valid_session
      assigns(:keyword).should eq(keyword)
    end
  end

  describe "GET new" do
    it "assigns a new keyword as @keyword" do
      get :new, {}, valid_session
      assigns(:keyword).should be_a_new(Keyword)
    end
  end

  describe "GET edit" do
    it "assigns the requested keyword as @keyword" do
      keyword = Keyword.create! valid_attributes
      get :edit, {:id => keyword.to_param}, valid_session
      assigns(:keyword).should eq(keyword)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Keyword" do
        expect {
          post :create, {:keyword => valid_attributes}, valid_session
        }.to change(Keyword, :count).by(1)
      end

      it "assigns a newly created keyword as @keyword" do
        post :create, {:keyword => valid_attributes}, valid_session
        assigns(:keyword).should be_a(Keyword)
        assigns(:keyword).should be_persisted
      end

      it "redirects to the created keyword" do
        post :create, {:keyword => valid_attributes}, valid_session
        response.should redirect_to(Keyword.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved keyword as @keyword" do
        # Trigger the behavior that occurs when invalid params are submitted
        Keyword.any_instance.stub(:save).and_return(false)
        post :create, {:keyword => { "name" => "invalid value" }}, valid_session
        assigns(:keyword).should be_a_new(Keyword)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Keyword.any_instance.stub(:save).and_return(false)
        post :create, {:keyword => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested keyword" do
        keyword = Keyword.create! valid_attributes
        # Assuming there are no other keywords in the database, this
        # specifies that the Keyword created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Keyword.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => keyword.to_param, :keyword => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested keyword as @keyword" do
        keyword = Keyword.create! valid_attributes
        put :update, {:id => keyword.to_param, :keyword => valid_attributes}, valid_session
        assigns(:keyword).should eq(keyword)
      end

      it "redirects to the keyword" do
        keyword = Keyword.create! valid_attributes
        put :update, {:id => keyword.to_param, :keyword => valid_attributes}, valid_session
        response.should redirect_to(keyword)
      end
    end

    describe "with invalid params" do
      it "assigns the keyword as @keyword" do
        keyword = Keyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Keyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => keyword.to_param, :keyword => { "name" => "invalid value" }}, valid_session
        assigns(:keyword).should eq(keyword)
      end

      it "re-renders the 'edit' template" do
        keyword = Keyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Keyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => keyword.to_param, :keyword => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested keyword" do
      keyword = Keyword.create! valid_attributes
      expect {
        delete :destroy, {:id => keyword.to_param}, valid_session
      }.to change(Keyword, :count).by(-1)
    end

    it "redirects to the keywords list" do
      keyword = Keyword.create! valid_attributes
      delete :destroy, {:id => keyword.to_param}, valid_session
      response.should redirect_to(keywords_url)
    end
  end

end
